sudo: required
dist: trusty
language: node_js
node_js:
- node
env:
  global:
  - DEPLOY_USER=deploy
  - DEPLOY_HOST=maya.elol.fr
  - DEPLOYS='mecs simple'
addons:
  ssh_known_hosts: maya.elol.fr
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- openssl aes-256-cbc -K $encrypted_b52bebe2eeaf_key -iv $encrypted_b52bebe2eeaf_iv
  -in deploy/deploy_rsa.enc -out deploy/deploy_rsa -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g angular-cli@webpack
- npm install -g karma
- npm install
- ng build
script: karma start config/karma.conf.js --single-run

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy/deploy.sh
  on:
    branch: master
